"""
Add pending_verification/approved/rejected to PostgreSQL paymentstatus ENUM

Revision ID: a1b2c3d4e5f6
Revises: de1d29df9408
Create Date: 2026-07-27 12:00:00.000000

Adds the three manual-payment status values to the paymentstatus ENUM
type so that PostgreSQL accepts them as valid column values:

  - pending_verification
  - approved
  - rejected

These values are already defined in the Python PaymentStatus enum
(backend.db.models.PaymentStatus) and used by the manual payment flow
(backend.services.manual_payment_service), but were never added to the
database ENUM type.

The migration is a no-op on SQLite (which uses VARCHAR for enums).
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "de1d29df9408"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# PostgreSQL ENUM type name — auto-generated by SQLAlchemy
# from the PaymentStatus Python enum class (lowercased).
PAYMENT_STATUS_ENUM = "paymentstatus"

# New values to add (in alphabetical order for reproducible DDL)
NEW_ENUM_VALUES = ["approved", "pending_verification", "rejected"]


def upgrade() -> None:
    bind = op.get_bind()
    is_postgres = bind.engine.name == "postgresql"

    if not is_postgres:
        # SQLite uses VARCHAR for enums — nothing to do.
        return

    # Add each new value to the PostgreSQL ENUM type.
    # ALTER TYPE ... ADD VALUE is safe inside a transaction
    # on PostgreSQL 9.3+. IF NOT EXISTS won't help here since
    # the syntax doesn't exist for ALTER TYPE ADD VALUE.
    for value in NEW_ENUM_VALUES:
        op.execute(
            f"ALTER TYPE {PAYMENT_STATUS_ENUM} ADD VALUE '{value}'"
        )


def downgrade() -> None:
    # ── WARNING ─────────────────────────────────────────────────
    # PostgreSQL does NOT support removing values from an ENUM type.
    # The only way to "undo" this migration is to:
    #   1. CREATE a new ENUM type without the values
    #   2. ALTER TABLE ... ALTER COLUMN ... TYPE ... USING ...
    #   3. DROP the old ENUM type
    #
    # This is a destructive, downtime-incurring operation that is
    # better done manually. For safety, downgrade is intentionally
    # a no-op — if you must revert, write a custom script.
    pass

